In [2]:
import matplotlib.pyplot as plt


In [3]:
img.shape

(333, 365, 4)

In [8]:
img = plt.imread('psj.png')
sliced = img[:,:,:3]
img = sliced.reshape((-1,333,365,3))
#np.expand_dims(sliced,axis=0)
img.shape

(1, 333, 365, 3)

In [9]:
import numpy as np
cimage = np.concatenate((img,img,img,img,img), axis=0)
cimage.shape

(5, 333, 365, 3)

In [12]:
cimage.reshape((5,3,333,365)) #RGB값 각자 처리하고 싶을떄 reshape해줌

array([[[[0.83137256, 0.8509804 , 0.8666667 , ..., 0.84313726,
          0.80784315, 0.827451  ],
         [0.84313726, 0.80784315, 0.827451  , ..., 0.88235295,
          0.8980392 , 0.8627451 ],
         [0.88235295, 0.8980392 , 0.8627451 , ..., 0.85490197,
          0.8666667 , 0.8862745 ],
         ...,
         [0.84313726, 0.8627451 , 0.8784314 , ..., 0.7882353 ,
          0.7490196 , 0.76862746],
         [0.7921569 , 0.74509805, 0.7647059 , ..., 0.79607844,
          0.7254902 , 0.90588236],
         [0.79607844, 0.7372549 , 0.827451  , ..., 0.87058824,
          0.8901961 , 0.90588236]],

        [[0.84313726, 0.8627451 , 0.8784314 , ..., 0.7921569 ,
          0.7490196 , 0.76862746],
         [0.7921569 , 0.74509805, 0.7647059 , ..., 0.7764706 ,
          0.72156864, 0.84313726],
         [0.7254902 , 0.6862745 , 0.81960785, ..., 0.87058824,
          0.8901961 , 0.90588236],
         ...,
         [0.827451  , 0.84705883, 0.8627451 , ..., 0.13333334,
          0.05882353, 0.0

In [13]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)

Instructions for updating:
non-resource variables are not supported in the long term


In [14]:
X_data = [[73.,80.,75.,],
          [93.,88.,93.,],
          [89.,91.,90.,],
          [96.,98.,100.,],
          [73.,66.,70.,]
         ]
y_data = [[152.],
         [185.],
         [180.],
         [196.],
         [142.]]

In [15]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [23]:
hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(Y-hypothesis))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
tf.train.GradientDescentOptimizer?

In [22]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(3001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis,train], feed_dict={X:X_data, Y:y_data})
    if step % 100 == 0:
        print(step,"Cost:", cost_val,'\nPrediction:\n', hy_val)

0 Cost: 2861.9668 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]]
100 Cost: 1.789065 
Prediction:
 [[153.03859]
 [183.54329]
 [181.20644]
 [196.80182]
 [140.09048]]
200 Cost: 1.708155 
Prediction:
 [[152.99164]
 [183.57559]
 [181.1922 ]
 [196.79037]
 [140.13387]]
300 Cost: 1.6314819 
Prediction:
 [[152.94594]
 [183.60704]
 [181.17836]
 [196.77919]
 [140.1761 ]]
400 Cost: 1.558845 
Prediction:
 [[152.9015 ]
 [183.63765]
 [181.16487]
 [196.76831]
 [140.21722]]
500 Cost: 1.4900503 
Prediction:
 [[152.85823]
 [183.66739]
 [181.15176]
 [196.75769]
 [140.25725]]
600 Cost: 1.4248439 
Prediction:
 [[152.81616]
 [183.69637]
 [181.139  ]
 [196.74731]
 [140.29623]]
700 Cost: 1.3630717 
Prediction:
 [[152.7752 ]
 [183.72455]
 [181.12659]
 [196.73718]
 [140.33417]]
800 Cost: 1.3045632 
Prediction:
 [[152.73538]
 [183.75198]
 [181.11456]
 [196.72736]
 [140.37114]]
900 Cost: 1.2491057 
Prediction:
 [[152.69662]
 [183.77867]
 [181.10281]
 [196.71773]
 [140.40712]]
